### ISSUE TITLE
Trade creation always fails with 500 INTERNAL_ERROR (reads work fine)

### ISSUE THREAD

**Issue by vald0s0h0** [GeneBO98/tradetally#342]
Hello
First, congrats on v2.7 the new UI is incredible!

Sadly the update broke trade creation for me. I drive everything through the API (reads and writes) with my own trade IDs, and this worked flawlessly before v2.7.

Works: auth with a `tt_live_` key (`trades:read`/`trades:write`), all reads (`GET /api/v1/trades`, `/summary/quick`, `/api/v1/health` → `200`), and validation (malformed body → correct `400`).

Broken: every valid trade creation returns `500`, and I can't create a trade manually in the UI either — same internal error:

`{"error":{"code":"INTERNAL_ERROR","message":"Something went wrong"},"requestId":"f10e0058-db1e-4147-8dd7-ae5d0bc736c2"}
`
Reproduced on `POST /api/v1/trades` and legacy `POST /api/trades`, open and closed trades, with/without `executions`, even a bare-minimum body:

`{"symbol":"ZTEST","side":"long","entryTime":"2026-06-04T15:36:59Z","entryPrice":1.23,"quantity":100}
`

Validation passes, so the crash is inside `Trade.create()`.

Environment: self-hosted via Docker. `/api/health` is `DEGRADED `but only benign backup/storage warnings (database OK, workers OK).

Thanks again for v2.7!

**Comment by GeneBO98** [comment]
I am terribly sorry about that. It was a huge update so there have been issues trickling in. This was due to an incomplete DB migration. This should now be resolved in the latest nightly image if you are using docker. I just pushed the fix so it will be built in about 5 minutes.

**Comment by vald0s0h0** [comment]
Hi,

Thank you for the quick fix and for pushing the update.

I've updated to the latest nightly Docker image and verified that the container is running the new version. Unfortunately, I'm still experiencing the same issue: every valid trade creation request returns a 500 INTERNAL_ERROR, and manual trade creation through the UI also fails with the same error.

Reads continue to work normally, and the database/worker checks still appear healthy. The issue seems to be limited to trade creation.

Please let me know if there's any additional information, logs, or diagnostics I can provide to help investigate further.

Thanks again for your help and for the work on v2.7

**Comment by GeneBO98** [comment]
Thanks for confirming it was still failing after the previous nightly.

I found another trade-creation crash from the logs: `Trade.create` was deriving `trade_date` with `.split("T")`, but in this path the timestamp can arrive as a Date object instead of a string, causing `timestampToUse.split is not a function` and returning 500 on POST `/api/trades`.

Fixed on `develop` in 19730e4: `fix: handle Date timestamps in trade creation`. I also added a regression test for Date-object entry timestamps. The next nightly Docker image should include this fix once the build completes.

Referenced issue: #342
